In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [43]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [44]:
df.Age.mean(), df.Salary.mean()

(38.77777777777778, 63777.77777777778)

In [45]:
# impute with mean
imputer = SimpleImputer(strategy='mean')
df_num = df[['Age','Salary']]
imputer.fit(df_num)
imputer.transform(df_num)

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [46]:
df.Age.median(), df.Salary.median()

(38.0, 61000.0)

In [47]:
# impute with median
imputer = SimpleImputer(strategy='median')
imputer.fit(df_num)
imputer.transform(df_num)

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 6.1e+04],
       [3.5e+01, 5.8e+04],
       [3.8e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [48]:
df = df.append({'Country':np.nan,'Age':20, 'Salary':65000, 'Purchased':np.nan},ignore_index=True,)

In [49]:
# impute with most frequent
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit(df)
imputer.transform(df)

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 48000.0, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 20.0, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes'],
       ['France', 20.0, 65000.0, 'No']], dtype=object)

In [50]:
# impute with most frequent
imputer = SimpleImputer(strategy='constant',fill_value=0)
imputer.fit(df_num)
imputer.transform(df_num)

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 0.0e+00],
       [3.5e+01, 5.8e+04],
       [0.0e+00, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [51]:
# combine fit and transform
imputer = SimpleImputer(strategy='constant',fill_value=0)
imputer.fit_transform(df_num)

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 0.0e+00],
       [3.5e+01, 5.8e+04],
       [0.0e+00, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [52]:
# save transformed data in a dataframe
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit(df)
X=imputer.transform(df)
df = pd.DataFrame(X,columns=['Country','Age','Salary','Purchased'])
df

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0  48000.0       Yes
5    France  35.0  58000.0       Yes
6     Spain  20.0  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
10   France  20.0  65000.0        No

# 2. Categorical Data

In [53]:
groups

ordered
jan,feb,mar
mon,sun,tue
young,mid,old

unordered
male and female

NameError: name 'groups' is not defined

In [ ]:
df['month'] = ['jan','mar','dec','jan','apr','mar','sep','jul','jan','jan','feb']
df

In [ ]:
df['month_no'] = df['month'].map({'jan':1,'feb':2,'mar':3,'apr':4,'may':5,'jun':6,
                                 'jul':7,'aug':8,'sep':9,'oct':10,'nov':11,'dec':12})
df

In [ ]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder

In [ ]:
country = df[['Country']]
country

In [ ]:
encoder = OneHotEncoder(sparse=False)
encoder.fit_transform(country)

In [ ]:
df[encoder.categories_[0].tolist()] = encoder.fit_transform(country).astype(int)
df